version: '2'
services:
    sullyboot-app:
        image: sullyboot
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://sullyboot-postgresql:5432/sullyBoot
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sullyboot-postgresql:
        extends:
            file: postgresql.yml
            service: sullyboot-postgresql
