package fr.sully.boot.domain.enumeration;

/**
 * The CategorieRGPD enumeration.
 */
public enum CategorieRGPD {
    GENETIQUE, BIOMETRIQUE, SANTE, ORIGINE, OPINIOONS, CONVICTIONS, SYNDICALE, VIE_SEXUELLE, PENALE, SECRET_PROFESSIONNEL, COMMUNICATION_ELECTRONIQUE, LOCALISATION, FINANCIERE, AUTRE
}
