package fr.sully.boot.domain.enumeration;

/**
 * The Source enumeration.
 */
public enum Source {
    PERSONNE, RELATION, CONSEILLER_PROFESSIONNEL, EMPLOYEUR, AUTRE_ENTREPRISE_PRIVEE, SERVICE_PUBLIC, JUSTICE_POLICE, SECURITEE_SOCIALE, BANQUE_ASSURANCE, MARKETING, AUTRE
}
